services:
  ffmpeg:
    image: ragedunicorn/ffmpeg:7.1.1-alpine3.22.1-2
    container_name: ffmpeg_concat_vp_umc
    volumes:
      - .:/data
    working_dir: /data
    command: -f concat -safe 0 -i files.txt -c copy merged.ogg
    networks:
      - ffmpeg_net

networks:
  ffmpeg_net:
    driver: bridge
